<?php if(Mage::getStoreConfig('townsidecookiebar/general/enabled') == 1 && Mage::getStoreConfig('web/cookie/cookie_restriction') == 0 && !isset($_COOKIE['townside_accept_cookies'])){ ?>
	<div id="townside-cookiebar-outer">
        <div class="page main townside-cookiebar-inner">
            
            <div class="actions townside-cookiebar-btn-con">
            	<button class="townside-cookiebar-btn-accept" onclick="clickTownsideCookieBar()"><?php echo $this->__('OKAY'); ?></button>
            	<a class="townside-cookiebar-learn" href="<?php echo Mage::getStoreConfig('townsidecookiebar/general/learn') ?>"><span><?php echo $this->__('Learn more'); ?></span></a>
            </div>
            <div class="townside-cookiebar-text"><?php echo Mage::getStoreConfig('townsidecookiebar/general/text') ?></div>
        	<div class="clear"></div>
        </div>
    </div>
    <script type="text/javascript">
    /* <![CDATA[ */
    function clickTownsideCookieBar() {
         Mage.Cookies.set('townside_accept_cookies', '{"1":1}', new Date(new Date().getTime() + 31536000 * 1000));
        if (Mage.Cookies.get('townside_accept_cookies')) {
            $('townside-cookiebar-outer').hide();
            //$$('.townside-cookiebar-outer').setStyle({ display:'none' });
        }    
        
    }
    /* ]]> */
    </script>
<?php } ?>
